name : BuildAndroidWindow
    
on: workflow_dispatch

jobs:  
    build-android-Windows:
        name: build install Android urho.Net on Windows
        runs-on: windows-latest
        steps:
           - name: Checkout repository
             uses: actions/checkout@v3
             with:
                submodules: recursive
           - name: Setup Android SDK and NDK and Java SDK
             run : pwsh -File ./Source/script/setup_android_windows.ps1
           - name: Install and Configure Mono
             run: pwsh -File ./Source/script/install_mono.ps1
           - name: build and install Windows urho.Net libs
             run : pwsh -File ./Source/script/build_install_urhonet_android_libs.ps1         

